name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: comics
  DOCKER_IMAGE_TAG: build-${{ github.sha }}
  SERVER_HOST: "3.68.167.84"
  SERVER_USERNAME: ubuntu
  SSH_PRIVATE_KEY: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAw6tECffUnvoqHjFrtcKvYMXH181dpEK9pccAQfxlej7JI8ad
JdgEUXPoHUBQznoT0mH+1V6qoe/OnbH+I5tjl1XgL36v3P+O0pRUN/OqpbEeQM1b
pJN9r4Pj6ytmiyTNFGv2XQfpuexNrdZo48LCb7i+fizXpdlFm+K0C25ps+mhQzYy
MXtt0aCkeoQiFBJrcWBmR3O9cR5CxyA/gjX76vsxLcBMfoZQ3+0M53yEzIY6WfXu
zljY44B9v+I8dAd1OfO2xXi0syVhhIPNrkNhygrcL4SAFjO8IbyOwZhMeuTcdCUu
DtbqX/Cyec1scOZOIi17+0cD75Iqg+HjmKosGQIDAQABAoIBAQCCbVYkItvKwMx0
ZdL7THOk2RFWCyGBTa+moljMo1ZtPw7KVykHQc/XD6DIZse2am9uDD5Wsgyhdv1N
5oiV6Y1gIjEW16aYdI0aVx8wUK8OVVrqLTkKIfpklVDGwJ5Q384H79M/vfeRJC+/
Ua2HLJp46DeqWW/BsGuS9nG3MPkqn8M1N5X/37/G65KDNQDLTcT9uLMvnwDjDdX4
P2ETGZs7nCl1PtmY2JPDiAWn6Ftu5oFjrIIk2tJfAdhQIDH7fMDEd8+ZiaMNXgM5
On7cmIKm16xsW1tjejSZXv0hzbUDW2e5NvP33gKSVu4sqhcYVmnvMDkwgwpL8PWr
hld0i54BAoGBAP540ke0/2mqCxtjpvXWmXNyZ0+tdT6b02ijKytD+n2bZNCXTG+m
wXH0FFfd7lDypOTHY+pthblaSWcDkaZ7f/LhRq7LhbTJgXn3l8N2lUmzext+pOut
bK5R7cV91MfPpeSz8zXtICbDjjlLZHPK7aQy6qqUxE08OSTVuAPOjJfZAoGBAMTY
DS3IB2bOWwx/juAjfEKptziNo80PTbGy/U4Ibq+C5X0cydxvNiNEc/hpZd2AIHI7
wMm0VPKB+gY6T4HF1bkPqT0/sfXeTO5GyKHoFGSdErskJLyWXC0l+8QA5oobVI/Y
0MWhToh95bVEg07iMWZpHaCZSY4XBvKJzSY9n85BAoGAIMd7ftUn2XqX9608gopk
NeTUvgTAB5KXBvGNzALzr15m/B+hLviyDnW8cR0bZ73506aDjl0RTrD8p5JkHqfl
8Wlna3i3/nO+g/GK0RjjXh0KjJ4hrGIoj8Pp9viggiSTYAR2HcovzA6AsYyuoePP
/Mi6RcLoDnLlgYMuMv9WSPECgYAUJ2LCCzbmyb38u5qvTDLOyH2f5rCcsDJuPTs+
IBLlGWvRsX7heOl8FuggyPnLAfFQgNmuTS5dXf1xYcr+KHlHZ1kWkkzwNYB+7PRh
z1c3LfXa/0pbnLF3Veo/GTCBd2bjC3nkoi1eQDWip48iJnqUV7LW3JrxV144uu8s
OScBgQKBgQDPw/N/E35h5xOAuWTSJqvhpg5VeRN0gEGRC7WYYW12kChe6q66YbH7
5N9VD/nZHgGsR0oKjlj/kY9mJcsiHDMoR6TTCFiynqxjKrkTNVc3Rrtz8QhDVPZx
E/ArAnUavetZGkL44MmENIsWkqHPS1a+PW9tuVHjxzaBxZHTK0tJBw==
-----END RSA PRIVATE KEY-----
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use --name mybuilder
          docker buildx build --platform linux/amd64 --push -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

      - name: Deploy Docker image to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            docker stop comics || true
            docker rm -f comics || true
            docker image rm ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} || true
            docker run -d --name comics -e POSTGRES_HOST=${{ env.DATABASE_HOST }} -e POSTGRES_USER=${{ env.DATABASE_USER }} -e POSTGRES_PASSWORD=${{ env.DATABASE_PASSWORD }} -p 8000:8000 ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
